model:
  hidden_channels: 64
  heads: [8, 8]
  dropout: 0.6

training:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.005
  weight_decay: 5e-4
  patience: 20
  min_delta: 1e-4

data:
  tickers_file: "data/raw/sp500tickers.txt"
  price_data_file: "data/processed/price_df.pkl"
  train_year: 2022
  test_year: 2023
  window_size: 20
  correlation_window: 60
  correlation_threshold: 0.3
  top_n: 20
  num_assets: 20

device: "cuda" 